//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRestaurant.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MainDb : DbContext
    {
        public MainDb()
            : base("name=MainDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sys_dict> sys_dict { get; set; }
        public virtual DbSet<sys_role> sys_role { get; set; }
        public virtual DbSet<sys_user> sys_user { get; set; }
        public virtual DbSet<zzdc_cpwlxh> zzdc_cpwlxh { get; set; }
        public virtual DbSet<zzdc_cpxx> zzdc_cpxx { get; set; }
        public virtual DbSet<zzdc_czxx> zzdc_czxx { get; set; }
        public virtual DbSet<zzdc_ddxq> zzdc_ddxq { get; set; }
        public virtual DbSet<zzdc_ddxx> zzdc_ddxx { get; set; }
        public virtual DbSet<zzdc_jhxq> zzdc_jhxq { get; set; }
        public virtual DbSet<zzdc_jhxx> zzdc_jhxx { get; set; }
        public virtual DbSet<zzdc_wllx> zzdc_wllx { get; set; }
        public virtual DbSet<zzdc_wlxhxq> zzdc_wlxhxq { get; set; }
        public virtual DbSet<zzdc_wlxx> zzdc_wlxx { get; set; }
        public virtual DbSet<zzdc_xsxq> zzdc_xsxq { get; set; }
        public virtual DbSet<zzdc_xsxx> zzdc_xsxx { get; set; }
        public virtual DbSet<sys_menu> sys_menu { get; set; }
        public virtual DbSet<sys_relation> sys_relation { get; set; }
        public virtual DbSet<zzdc_cplx> zzdc_cplx { get; set; }
        public virtual DbSet<zzdc_czlx> zzdc_czlx { get; set; }
    }
}
