//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRestaurant.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zzdc_ddxx
    {
        public int id { get; set; }
        public int czxx_id { get; set; }
        public System.DateTime cjsj { get; set; }
        public string cjr { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> jdsj { get; set; }
        public string jdr { get; set; }
        public string jd_remark { get; set; }
        public Nullable<System.DateTime> fksj { get; set; }
        public string fkr { get; set; }
        public Nullable<double> yxfk { get; set; }
        public Nullable<double> sjfk { get; set; }
        public Nullable<int> zd_id { get; set; }
        public string pj { get; set; }
    }
}
