//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRestaurant.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zzdc_jhxx
    {
        public int id { get; set; }
        public System.DateTime ydsj { get; set; }
        public System.DateTime cjsj { get; set; }
        public string cjr { get; set; }
        public string remark { get; set; }
    }
}
