//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRestaurant.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zzdc_jhxq
    {
        public int id { get; set; }
        public int wlxx_id { get; set; }
        public double jhsl { get; set; }
        public string jhbz { get; set; }
        public Nullable<double> dhsl { get; set; }
        public string dhbz { get; set; }
        public int zd_id { get; set; }
    }
}
