//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRestaurant.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zzdc_xsxx
    {
        public int id { get; set; }
        public System.DateTime yxqssj { get; set; }
        public System.DateTime yxjssj { get; set; }
        public string yxbz { get; set; }
        public System.DateTime cjsj { get; set; }
        public string cjr { get; set; }
        public Nullable<System.DateTime> xsqssj { get; set; }
        public Nullable<System.DateTime> xsjssj { get; set; }
        public string xsbz { get; set; }
        public Nullable<System.DateTime> lrsj { get; set; }
        public string lrr { get; set; }
    }
}
