//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRestaurant.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zzdc_xsxq
    {
        public int id { get; set; }
        public int xsxx_id { get; set; }
        public int cpxx_id { get; set; }
        public double jhbz { get; set; }
        public Nullable<double> dhsl { get; set; }
    }
}
